#!/usr/bin/env python
"""
Simple tool to display term rankings generated by NMF/LDA/SKM, stored in one or more PKL
files.
"""
import logging as log
from optparse import OptionParser
import unsupervised.rankings, unsupervised.util

# --------------------------------------------------------------

def main():
	parser = OptionParser(usage="usage: %prog [options] ranking_file1 ranking_file2 ...")
	parser.add_option("-t", "--top", action="store", type="int", dest="top", help="number of top terms to show", default=10)
	parser.add_option('-d','--debug',type="int",help="Level of log output; 0 is less, 5 is all", default=3)
	parser.add_option("-l","--long", action="store_true", dest="long_display", help="long format display")
	(options, args) = parser.parse_args()
	if( len(args) < 1 ):
		parser.error( "Must specify at least one ranking set file" )
	log.basicConfig(level=max(50 - (options.debug * 10), 10), format='%(asctime)-18s %(levelname)-10s %(message)s', datefmt='%d/%m/%Y %H:%M',)

	# Load each cached ranking set
	for in_path in args:
		log.info( "Loading terms from %s ..." % in_path )
		(term_rankings,labels) = unsupervised.util.load_term_rankings( in_path )
		m = unsupervised.rankings.term_rankings_size( term_rankings )
		log.info( "Set has %d rankings covering up to %d terms" % ( len(term_rankings), m ) )
		if options.long_display:
			print( unsupervised.rankings.format_term_rankings_long( term_rankings, labels, min(options.top,m) ) )
		else:
			print( unsupervised.rankings.format_term_rankings( term_rankings, labels, min(options.top,m) ) )

# --------------------------------------------------------------

if __name__ == "__main__":
	main()
